DockYard-Academy/curriculum

reading/arithmetic.livemd

add period in arithmetic section

---

reading/processes.livemd

From flowchart to sequence diagram
I have not updated all the diagrams yet, if you think this is the way to go I can update the rest here.

Updated three diagrams

---

exercises/naming_numbers.livemd

Submitting the ExUnit test written for the 'Naming Numbers' exercise.

Add ExUnit test for 'Naming Numbers' exercise.

---

exercises/family_tree.livemd
reading/processes.livemd

Fixes #12 and improves family tree diagram

Family tree inconsistencies

---

exercises/treasure_hunt.livemd

typo in treasure hunt exercise

---

reading/arithmetic.livemd

Fixed typo in Arithmetic.livemd

Fixed typo in Arithmetic

---

reading/maps.livemd

fixed 'ap' to 'map' in Manipulating Maps section

---

reading/command_line.livemd
reading/git.livemd

2 commits:
* i wont make too many style PRs but this one seems ok
* fix `Git` to `git` in 2 examples
feel free to just close the commits and make either change yourself.

1 style change and 2 capitalization changes

---

reading/livebook.livemd

found an incomplete sentence and gave it a shot.
of course feel free to reword as you prefer!

updated sentence fragment about markdown cells

---

exercises/item_generator.livemd

Changed all_items arity from 3 to 2.

Typo fix item_generator - all_items/2

---

utils/lib/solutions.ex

Fix difference between what the exercice is asking vs what is actually tested
I'm not really sure if you would prefer doing a big pull request or multiple ones when encountering issues so feel free to tell me :D

Fix solutions.ex for shopping_list

---

reading/built-in_modules.livemd

There was a missing codeblock in an area where a student should add their own solution, This PR should add the codeblock so the student doesn't need to manually add it.

Add codeblock to built-in modules challenge

---

exercises/sublist.livemd
start.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

basic implementation for Sublist exercise

[IMPLEMENTED] Exercise: Sublist

---

exercises/sublist.livemd

duh, committed the solution in the exercise. removed...

[FIX] Sublist: Committed solution in the exercise!

---

utils/lib/feedback.ex
utils/lib/form.ex
utils/lib/solutions.ex

fixing bug where the field for diagram2 was unavailable; see images.

[FIX] Boolean Operators: Missing input field; [IMPLEMENTED] number_wordle solution

---

exercises/fun_formulas.livemd
exercises/habit_tracker.livemd
reading/match_operator.livemd
utils/lib/feedback.ex

created `:percentage_random` to check percentage when `completed_items` and `total_items` are chosen at random.

fix typos, create feedback for percentage with random inputs

---

exercises/rpg_dialogue.livemd
reading/structs.livemd

resolve remaining running issues

---

reading/built-in_modules.livemd

add list module to built-in modules reading

---

reading/command_line.livemd

- use common OS name
- use the right prompt by OS

Fix markdown and wordings

---

reading/git.livemd

- Github -> GitHub
- git -> Git
- bump vega_lite dependency
- add kino_vega_lite dependency
- reword `ea` shortcut instruction
- fix missing markdown

Misc. changes to Git page

---

exercises/github_collab.livemd
exercises/github_engineering_journal.livemd
exercises/livebook_recovery.livemd

- github -> GitHub
- git -> Git
- fix markdown
- remove trailing spaces

Misc. changes to exercise pages

---

reading/comments.livemd

- add missing keyboard icon
- add missing and rename OS names

Misc. changes to comments page

---

exercises/measurements.livemd

This function should be implemented by students.

Remove implementation of increments/1 from measurements exercise.

---

reading/arithmetic.livemd

- name the money handling library explicitly
- remove trailing space
- add arity to div and rem function
Note that it took a while for the browser to load this page.

Misc. change to arithmetic page

---

reading/built-in_modules.livemd

The is intended as an exercise for the student

Remove solution intended for the student

---

exercises/item_search.livemd
utils/lib/feedback.ex

A list of maps is expected not a list of Item structs.
Remove duplicated test.

Remove typo and duplicate test

---

reading/computer_hardware.livemd

The cell below has the content this cell is referring to with the correct URL for Kino.

Remove unused livebook cell

---

reading/streams.livemd

Stream.unfold returns the end of the list

Typo and exposition fix

---

exercises/item_search.livemd

change code cell to a block cell
this content is pseudocode

Item Finder

---

reading/documentation_and_static_analysis.livemd
reading/mix.livemd
reading/rdbms.livemd
reading/scripts.livemd

Partially resolve https://github.com/DockYard-Academy/beta_curriculum/issues/156

Use relative path when linking in reading pages

---

.github/workflows/elixir.yml
utils/lib/feedback.ex
utils/lib/solutions.ex

We also bump the Erlang/Elixir version to match asdf's .tool-versions

Mix format utils and add relevant Github Actions task

---

.github/workflows/elixir.yml
utils/.credo.exs
utils/lib/animate.ex
utils/lib/feedback.ex
utils/lib/feedback/assertion.ex
utils/lib/slide.ex
utils/lib/solutions.ex
utils/lib/utils.ex
utils/lib/visual.ex
utils/test/utils_test.exs

There are still remaining issues pending your take on this.

Add Credo config and resolve some issues raised

---

.github/workflows/elixir.yml
exercises/portfolio_blog_live_search.livemd
exercises/portfolio_mock.livemd
utils/.credo.exs
utils/lib/animate.ex
utils/lib/feedback.ex
utils/lib/feedback/assertion.ex
utils/lib/slide.ex
utils/lib/solutions.ex
utils/lib/utils.ex
utils/lib/visual.ex
utils/test/utils_test.exs

Add credo config

---

exercises/boolean_operators.livemd
utils/lib/feedback.ex

Still in order to help (and learn Elixir), I saw this issue https://github.com/DockYard-Academy/beta_curriculum/issues/170 and think I can help with it.
I tried with `TestedCell`, maybe I should use `ExerciseCell` instead?

Boolean Operators exercise: Replace Utils.feedback with TestedCell

---

exercises/boolean_operators.livemd

fix boolean operators smart cell

---

exercises/fun_formulas.livemd
utils/lib/feedback.ex

This time I correctly used the input to add hints and assertions, much easier 😂

Fun Formulas exercise: Replace Utils.feedback with TestedCell

---

reading/livebook.livemd

Changed the keybind to alt+shift+f

Changed the formatting keybids for the livebook lesson

---

reading/book_search_authors.livemd

Changed text_input to search_input

Changed to search_input

---

exercises/card_counting.livemd
utils/lib/feedback.ex

Card Counting exercise: Replace Utils.feedback with TestedCell

---

exercises/habit_tracker.livemd
utils/lib/feedback.ex

Habit Tracker exercise: Replace Utils.feedback with TestedCell

---

exercises/guessing_games.livemd
utils/lib/feedback.ex

Guessing Games exercise: Replace Utils.feedback with TestedCell

---

exercises/card_counting.livemd

ref: https://github.com/DockYard-Academy/beta_curriculum/pull/190#discussion_r933630399

Add details to Card Counting description

---

exercises/rock_paper_scissors.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Rock Paper Scissors exercise: Replace Utils.feedback with TestedCell

---

exercises/shopping_list.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Shopping List exercise: Replace Utils.feedback with TestedCell

---

utils/lib/solutions.ex

I saw a bit late the content of the `utils/lib/solutions.ex` file.
This PR is to remove some of the content of this file, that should already be removed while I replace `feedbacks` with `TestedCell`

Cleanup: Remove solutions of already removed feedbacks

---

data/large_data
reading/file.livemd

file did not exist
made instructions more clear
fix typo

fix miscellaneous issues

---

exercises/family_tree.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Family Tree exercise: Replace Utils.feedback with TestedCell

---

exercises/naming_numbers.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Naming Numbers exercise: Replace Utils.feedback with TestedCell

---

exercises/rpg_dialogue.livemd
utils/test/utils_test.exs

Tried to resolve the issue https://github.com/DockYard-Academy/beta_curriculum/issues/213
Not sure if it's the simpler / good way to do this

Add test to ensure TestedCell show_editors are found

---

exercises/anagram_solver.livemd
reading/apis.livemd
utils/test/utils_test.exs

Issue: https://github.com/DockYard-Academy/beta_curriculum/issues/222

Add test to ensure broken links are found

---

reading/comparison_operators.livemd

Suggestions for typo corrections Week 1 / Basics / Reading / Comparison Operators

fix: ⌨️  address typos

---

reading/atoms.livemd
reading/lists.livemd
reading/tuples.livemd
utils/lib/feedback.ex

Fix  typos

---

exercises/custom_rock_paper_scissors.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Custom Rock Paper Scissors exercises: Replace Utils.feedback with TestedCell

---

exercises/bottles_of_soda.livemd
exercises/custom_enum_with_reduce.livemd
reading/enum.livemd

Suggestions for typo corrections

fix: ⌨️  address potential typos

---

exercises/custom_enum_with_reduce.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Custom Enum exercises: Replace Utils.feedback with TestedCell

---

exercises/measurements.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Measurements exercises: Replace Utils.feedback with TestedCell

---

exercises/bottles_of_soda.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

**Bottles of Soda:**
**Bottles of ???:**

Bottles of Soda exercises: Replace Utils.feedback with TestedCell

---

exercises/item_generator.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex

Item Generator exercises: Replace Utils.feedback with TestedCell

---

reading/phoenix_authentication.livemd

I'll add explanatory comments in the diff.

Fixes & improvements for the Phoenix Auth reading.

---

start.livemd

Slightly more friendly mermaid demo/test.

---

.vscode/snippets.code-snippets
start.livemd

Fill in start.livemd outline

---

reading/exunit.livemd

The ExUnit page was rather long, consider splitting it into two parts?

Misc fixes for exunit page

---

README.md
utils/lib/mix/tasks/update_readme_outline.ex

This PR:
- Creates a mix task to update the readme with course outline from `start.livemd` file
- Updates the current README with course outline from `start.livemd`
Closes https://github.com/DockYard-Academy/beta_curriculum/issues/151

create mix task to update course outline on readme

---

reading/arithmetic.livemd
reading/comparison_operators.livemd
reading/strings.livemd

Just some text changes to the W1D2 reading sections

Add reading updates to W1D2 reading

---

reading/rdbms.livemd

I kept having issue connecting to the database, any ideas?
Database connection was connecting on first load, after `ea`, but raised error when re-evalauted:

Misc fixes for rdbms page

---

reading/apis.livemd

Should we replace the Elixir libraries used in this page with:
- https://github.com/wojtekmach/req (simpler) or https://github.com/sneako/finch (modern)
- https://github.com/michalmuskala/jason (popular)
What do you think?

Misc fixes for APIs page

---

exercises/public_chat_api.livemd

> We have created a public chat application you can
Do you know where is the public chat application is?

Fix http ver in public chat api exercise

---

reading/supervisors.livemd

Add Mermaid Diagrams to Supervisor strategies

---

reading/lists.livemd

- add missing period
- beta_curriculum/reading/lists.livemd
n/a

Add missing period

---

exercises/anagram.livemd

[Fixes #332] Removes is prefix from Anagram exercise.

---

exercises/portfolio_blog_search.livemd

[Fixes #331] Fix URL typo in Markdown block.

---

README.md
exercises/math_game.livemd
exercises/measurements.livemd
reading/supervisors.livemd
start.livemd
utils/README.md
utils/lib/mix/tasks/add_git_section.ex
utils/lib/mix/tasks/add_navigation.ex
utils/lib/mix/tasks/bc.ex
utils/lib/mix/tasks/format_headings.ex
utils/lib/mix/tasks/format_notebooks.ex
utils/lib/mix/tasks/update_documentation_links.ex
utils/lib/mix/tasks/update_readme_outline.ex

This PR introduces a `mix bc` Mix tasks to organize and group all Mix Tasks related to Betta Curriculum. We also re-format and updates all Livebooks as well.

Refactor and update Mix Tasks

---

reading/guards.livemd

I think this should accept numbers based off of the next cell.

Swap integer with number

---

reading/control_flow.livemd

I just changed the grade range on C -> 55 - 59 to 55 - 69

fixed number range on control flow lesson

---

exercises/counting_votes.livemd

Corrects module name in docstrings

Issue 416 - Correct module name

---

reading/modules.livemd

As you break down the named function, use the "hello world" in step 3.
I added "world" to the function body to keep the train of thought.

added world to the greeting to follow throught with the train of thought

---

reading/enum.livemd

Fixed typo

---

exercises/fun_formulas.livemd
exercises/habit_tracker.livemd

Minor typo fix in `exercises/fun_formulas.livemd` and `exercises/habit_tracker.livemd`.

Fix typo in fun formulas and habit tracker

---

exercises/saferange.livemd
start.livemd
utils/lib/feedback.ex

Jeff Helman asked about Elixir providing some sort of feedback when the step value to a range "doesnt make sense".
I use this question to introduce the standard of functions with name! throw exceptions instead of providing a return value for the unadorned function.
This is just "thinking out loud" in code. So, please no big deal.

WIP: New bonus exercise: Safe Ranges

---

exercises/rock_paper_scissors_lizard_spock.livemd

Added Big Bang Theory clip that sources the original game creator and explains the rules.

Add video describing game

---

reading/built-in_modules.livemd

Issue #440 - Cleaned up reading

---

exercises/mad_libs.livemd
reading/lists.livemd

Fix minor typos in mad libs and lists.

fix minor typos

---

exercises/book_search.livemd
exercises/filter_values_by_type.livemd
exercises/tic-tac-toe.livemd
reading/built-in_modules.livemd
reading/reduce.livemd

Issues:
- [Navigation is broken on ](https://github.com/DockYard-Academy/beta_curriculum/issues/449)
- [Filter Values By Type](https://github.com/DockYard-Academy/beta_curriculum/issues/448)

Navigation fixed & Fixed test

---

exercises/filter_values_by_type.livemd

Corrected typo in test case

---

exercises/tic-tac-toe.livemd
exercises/weighted_voting.livemd
reading/reduce.livemd

Content review

---

exercises/card_counting.livemd

was spelled "dealth" should be "dealt"

correct spelling error

---

reading/pattern_matching.livemd

The example solution was not hidden.

hide example solution

---

README.md
exercises/math_with_guards.livemd
exercises/message_validation.livemd
exercises/metric_conversion.livemd
exercises/rps_guards.livemd
exercises/rps_pattern_matching.livemd
exercises/treasure_matching.livemd
reading/advanced_pattern_matching.livemd
reading/computer_hardware.livemd
reading/guards.livemd
reading/polymorphism.livemd
reading/protocols.livemd
reading/regex.livemd
reading/strings_and_binaries.livemd
start.livemd

closes  #483
Also includes some small review for Strings and Regex

split pattern matching and guard sections

---

exercises/message_validation.livemd

remove solution from message validation exercise

---

exercises/rollable_expressions.livemd

Some test cases in the exercise had dice formats that did not match the URL being generated.
Removed solution from exercise entry area.

Correct test cases and remove solution from student input area

---

exercises/_template.livemd
exercises/drill-enum1-replace-nils.livemd
exercises/drill-enum2-replace-nils.livemd
exercises/drill-patternmatching-replace-nils.livemd
exercises/drill-reduce-replace-nils.livemd
start.livemd
utils/lib/notebooks.ex

going to mark this DRAFT so you review; dont want accidental commit.
give this to someone in the beta class to review? jon, andrew, bill?

Drill lists replace nils

---

exercises/wordle_application.livemd

closes #521

---

exercises/math_module_testing.livemd

Small change to make instructions have correct arity.

fixed subtract arity

---

exercises/wordle_application.livemd
reading/exunit_with_mix.livemd

Fix wordle tests

---

reading/regex.livemd

Resolves issue #507 
Please let me know if anything else is required

Change recommendation from Elixre to Regexr

---

reading/book_search_book_content.livemd
reading/mix.livemd

Some of the links to the faker docs were broken, essentially tackling the following issue
- #535

fix: faker broken links

---

exercises/battle_map.livemd
utils/lib/feedback.ex
utils/lib/solutions.ex
utils/test/solutions_test.exs

Fix for #513 
* Fixed some of the examples/tests. Also provided a few `false` examples
* Updated the Example solution to match the solution (the actual solution seems fine)
* Run the examples as a moduledoc test
The last commit is a bit speculative. I saw it in a blog post once and always wanted to try it :smile: 
It seems to only see changes when you recompile before running the tests.
So a developer workflow would be like `mix clean && mix test` which is a bit awkward (but could be automated).
However, it would work great in CI.
What do you think?

Battle Maps docs

---

exercises/fibonacci.livemd
exercises/lucas_numbers.livemd

Fix Fibonacci and Lucas number exercises

---

reading/processes.livemd

Processes Typo fix

---

exercises/timer.livemd

Removed duplicate instance of the word "timer".

timer.livemd fix fix a word

---

exercises/pokemon_api.livemd
exercises/spoonacular_recipe_api.livemd
reading/apis.livemd

I was having trouble with this reading assignment compiling due to missing Poison module. So I added the dep into the header.

added poison dependency

---

reading/task.livemd

I'm not sure how the Github action that does spell checking let you merge that one in.

Typo correction

---

reading/web_servers.livemd

Small clean-up items in the http section.

Fixed dependency error and small typo in text

---

reading/generic_server.livemd

Add Elixir Cells as suggested in #593

Add evaluaton cell to Client / Server APIs subsection

---

reading/generic_server.livemd

Grammar fix as suggested in #573

Fix generic_server.livemd grammar issue

---

exercises/document_tools.livemd

Updated the Example Solution for word_count() to use Streams and reduce overall complexity.

updated example around word_count to be more streamlined and use Stream

---

exercises/github_collab.livemd

I've assumed here that the extra asterisks aren't intended to indicate a special context or reference some other content on the page.

Typos in exercises/github_collab

---

exercises/blog_search.livemd
reading/phoenix_authentication.livemd
reading/schemas_and_migrations.livemd
start.livemd

Create schemas and migrations reading material (not exercises)

Schemas and migrations

---

exercises/blog_comments.livemd
reading/book_search_books.livemd
start.livemd

Improved book search one-to-many content with deeper explanations and exercise improvements to reflect how the portfolio project is now a blog project.

book search books review

---

README.md
exercises/blog_comments.livemd
exercises/blog_migration.livemd
exercises/portfolio_auth_blog_page.livemd
reading/book_search_books.livemd
reading/book_search_tags.livemd
reading/phoenix_authentication.livemd
reading/schemas_and_migrations.livemd

fix failing tests and run mix tasks

One to many

---

exercises/blog_migration.livemd
reading/schemas_and_migrations.livemd

schemas and migrations content review

---

exercises/blog_authentication.livemd
reading/phoenix_authentication.livemd
start.livemd

- convert portfolio auth exercise to the new blog project
- add overview of authentication/authorization to reading material.
- added link to diary example project

Phoenix authentication content updates

---

exercises/blog_authentication.livemd
reading/book_search_authors.livemd
reading/book_search_book_content.livemd
reading/book_search_books.livemd
reading/book_search_tags.livemd
reading/phoenix_authentication.livemd
start.livemd

Moved book_search project to DYA org, updated links to match the new URL

Move projects to dy org

---

README.md
exercises/blog_comments.livemd
exercises/blog_setup.livemd
reading/book_search_books.livemd
reading/book_search_books_constraint.livemd
reading/phoenix_and_ecto.livemd
start.livemd

Simplified the reading material to spend more time on using associations in the IEx shell.

Ecto one to many content simplification

---

reading/comprehensions.livemd

Improve wording of a Your Turn exercise

---

reading/book_search_deployment.livemd

book_search is the repo, book_content is the branch.

Fixed repo address

---

exercises/caesar_cypher.livemd

Expanded upon Caesar Cypher solution provided in #682

Waranlogesh patch 3

---

exercises/math_with_protocols.livemd

Fix math protocol doc test

---

CONTRIBUTING.md
reading/pic_chat_infinite_scroll.livemd
reading/pic_chat_messages.livemd

688 reduce the number of review questions and convert the into learning outcomes in picchat messages

---

reading/book_search_deployment.livemd

674 booksearch deployment setup ci requires personal access token

---

reading/processes.livemd

close #602 
Added to process reading instead of task reading as was originally suggested.

add soul of erlang to reading

---

exercises/traffic_light_server.livemd

fix traffic light broken doctests

---

reading/command_line.livemd
reading/iex.livemd
reading/io.livemd

add scripts and IO to early content

---

exercises/pascals_triangle.livemd

fix typo in pascals triangle

---

exercises/battle_map.livemd

close #513 which was already resolved, but this is related.

use ExUnit tests instead of doctest for battle map

---

exercises/caesar_cypher.livemd

add non-alphabet example to caesar cypher

---

exercises/caesar_cypher.livemd
reading/reduce.livemd

465 show how to use multiple accumulators in enumreduce section

---

reading/keyword_lists.livemd
reading/livebook.livemd
reading/maps.livemd
reading/strings.livemd

389 add explanation of making new code cells to livebook reading

---

exercises/github_collab.livemd

convert github collab into a multi person project

---

reading/apis.livemd
reading/comments.livemd
reading/io.livemd
reading/pic_chat_image_upload.livemd
reading/strings.livemd

730 use jason instead of poison in api section

---

exercises/rock_paper_scissors_lizard_spock.livemd

Not too sure leaving `"Player 2 Wins!"` return value for the last doctest was intentional. In that case please feel free to close or let me add a note suggesting the doctest needs to be fixed.

Fix Rock Paper Scissors Lizard Spock Draw test

---

reading/modules.livemd

clarify mutli param example your turn section

---

exercises/consumable_protocol.livemd

PR for Issue #829
Fixed 3 typos.
close #829

fixed 3 typos in consumable_protocol.livemd

---

exercises/animal_generator.livemd

Moved code into code cell

---

exercises/filter_values_by_type.livemd
exercises/measurements.livemd
reading/mix.livemd
reading/typespecs.livemd

Add a reminder to download dependencies after including dialyxir in mix.exs file.

Typespecs add deps.get for dialyxir

---

exercises/filter_values_by_type.livemd
exercises/measurements.livemd
exercises/stack_server.livemd
reading/mix.livemd
reading/typespecs.livemd

Issue #851: Stack Server "it's" -> "its"

---

reading/file.livemd

This would fix the typo in [Issue #842](https://github.com/DockYard-Academy/curriculum/issues/842)

"fix typo in File Reading"

---

exercises/score_tracker.livemd

Fixes the double "will" issue raised in [Issue # 859](https://github.com/DockYard-Academy/curriculum/issues/859).

Fix typo in Score Tracker

---

exercises/score_tracker.livemd
reading/match_operator.livemd

Fixes the issue found in [#868](https://github.com/DockYard-Academy/curriculum/issues/868).

Match operator example solution

---

exercises/with_points.livemd

It appears that someone saved this exercise with an existing solutions already written out.

With Points: remove existing solution from exercise

---

exercises/filter_values_by_type.livemd
exercises/tic-tac-toe.livemd
reading/built-in_modules.livemd

Add navigation section for `Built-In Modules` and `Tic-Tac-Toe` and update the doctest in `Filter Values By Type` to include the empty list.

update navigation sections and fix doctest

---

exercises/file_system_todo_app.livemd

The doctests currently fail due to file persistence. Unlike GenServers, you can't can't simply start a new link/pid and begin afresh!
The current doctests will still fail if the code is run repeatedly, so it's not a silver bullet, though I'm not currently sure of a better approach except for simply removing the doctests entirely.

File System Todo: fix doctests

---

start.livemd

move lessons to bonus section WIP

---

.tool-versions
exercises/rock_paper_scissors_lizard_spock.livemd

Special thanks to @BrooklinJazz for the amazing guidance

Add rock paper scissors lizard spock solution example

---

reading/pic_chat_image_upload.livemd

This PR fix the issue https://github.com/DockYard-Academy/curriculum/issues/937
error prone -> error-prone
you server -> your server
an file -> a file
Amazing S3 -> Amazon S3

Fixed typos on Pic chat image upload reading

---

reading/protocols.livemd

This PR add video asked in https://github.com/DockYard-Academy/curriculum/issues/911

Added video to protocols reading

---

reading/ecto_changeset.livemd

This PR fix https://github.com/DockYard-Academy/curriculum/issues/893

Fixed typos on Ecto changeset reading

---

reading/phoenix_and_ecto.livemd

This PR fix https://github.com/DockYard-Academy/curriculum/issues/904

Fixed typo on Phoenix and Ecto reading

---

reading/rdbms.livemd

Fix typo from https://github.com/DockYard-Academy/curriculum/issues/896

Fixed typo on RDMS reading

---

reading/enum.livemd

This PR fix this issue https://github.com/DockYard-Academy/curriculum/issues/863

Fixed Enum.any?/2 links in Enum reading

---

exercises/sign_up_form.livemd
reading/deprecated_liveview_and_ecto.livemd
reading/supervisors.livemd

Minor issues

---

reading/deprecated_liveview_and_ecto.livemd

how how -> how in deprecated reading material

---

CONTRIBUTING.md
README.md
exercises/capstone_entity_relationship_diagram.livemd
exercises/games_supervised_score_tracker.livemd
exercises/group_project_blog.livemd
exercises/stack.livemd
exercises/supervised_stack.livemd
exercises/task_drills.livemd
start.livemd
utils/test/test_helper.exs

Task Drill Solutions

---

reading/atoms.livemd

add missing quote to HelloWorld string

---

exercises/genserver_drills.livemd

Fix genserver drills exercise State description and example code

---

exercises/score_tracker.livemd
reading/file.livemd
reading/genservers.livemd
reading/phoenix_authentication.livemd
reading/task.livemd

Edit: added another commit fixing a typo in the GenServer reading
Also, while I have your attention, I DM'd you on Twitter a while ago looking into if the elixir hack-a-thing still takes place. If you could clue me in on that, I'm interested. Thanks!

corrected mixed up binary/term functions in file reading

---

reading/computer_hardware.livemd

Refactor: Use lowercase letter for variable in Computer Hardware 

---

reading/recursion.livemd

Fix capitalization

---

reading/guards.livemd

Fix guards docs links

---

reading/picchat_emails.livemd

Add missing comma

---

reading/maps.livemd

Update maps.livemd - Fix arrow description
