DockYard-Academy/curriculum

README.md
The course outline uses inconsistent and partially-incorrect indentation for the unordered list. I fixed the indentation, which changed the indentation in the browser somewhat. I think the changes are for the better, but you might want to confirm the outline looks ok at [the rendering of this branch's README](https://github.com/houhoulis/beta_curriculum/tree/readme_grammar_spelling_markdown).
=> Spelling, grammar, and markdown fixes in README.md

reading/modules.livemd
'\\' should have been used instead of '//' for default arguments
=> typo in reading/modules

reading/enum.livemd
Replaced 3 with 2 as the guide tells to convert [1,2] not [1,3]
=> Typo in enum.livemd

utils/lib/form.ex
For the answer to be `==` the comparison must be between `9` and `9.0`, not `0` and `9.0`.
=> fix typo in comparison operators form

exercises/mad_libs.livemd, utils/lib/feedback.ex
corrected name of the feedback macro to be implemented. Also, if the user binds one of the variables to a non-binary type, such as number or nil, the livebook evaluator throws an error before the assertion macro is implemented. (See picture below).
This happens because using non-binary values in string concatenation throws an error in Elixir (note that this does not happen in the next cell where string interpolation is used instead.)
I tried moving the `Utils.feedback` code before the `madlib`, but then `madlib` is undefined and that again causes an error. Perhaps there's a way to catch any errors thrown by the evaluator and show them alongside the feedback from the `feedback` macro?
=> fix typo in startup mad libs exercise

exercises/guessing_games.livemd
This is a small typo fix. The exercise should have thee different choices Correct, Too low, and Too high.
=> Fix typo in Guess the Number exercise

README.md
This ensures user can quickly copy and paste these instructions. We also
add link to these software mentioned.
=> Fix markdown, examples, and wording in Quickstart

exercises/shopping_list.livemd
In `Utils.Feedback`  shopping_list_with_quanties is passed to `feedback/2`, not shopping_cart_with_quantities. This fixes the following error message:
"Something went wrong, feedback does not exist for shopping_cart_with_quantities. Please speak to your teacher and/or reset the exercise."
=> fix typo that leads to error message on correct solution submission

utils/lib/feedback.ex, utils/lib/solutions.ex
Pattern matching fails when the student's solution parent's list is [ygraine, uther] instead of [uther, ygraine] since list order can not be guaranteed for a student's solution.
=> Fix list order not guaranteed

.github/workflows/elixir.yml, utils/lib/solutions.ex
This resolved issues encountered when running `mix compile --warnings-as-error`. We also added a task for this command in GitHub Actions.
```
$ cd utils
$ mix clean
$ mix compile --warnings-as-error
Compiling 14 files (.ex)
warning: clauses with the same name and arity (number of arguments) should be grouped together, "def row/1" was previously defined (lib/solutions.ex:1004)
lib/solutions.ex:1014
warning: variable "h" is unused (if the variable is not meant to be used, prefix it with an underscore)
lib/solutions.ex:1034: Utils.Solutions.Sublist.sublists/2
warning: variable "money" is unused (if the variable is not meant to be used, prefix it with an underscore)
lib/solutions.ex:1289: Utils.Solutions.Money.convert/2
Generated utils app
```
=> Fix compilation warnings and add check task to GitHub Actions

reading/command_line.livemd, utils/mix.exs, utils/mix.lock
This resolves the warnings below when Mix install the deps in Command
Line page.
```
warning: Kino.VegaLite.new/1 is undefined (module Kino.VegaLite is not
available or is yet to be defined
warning: Kino.VegaLite.push_many/2 is undefined (module Kino.VegaLite is
not available or is yet to be defined)
```
=> Resolve warnings on undefined Kino.VegaLite's functions

.github/workflows/elixir.yml, utils/lib/feedback.ex
List of warnings:
- warning: use of operator < has no effect
- warning: variable "acc" is unused
- warning: variable "get_answers" does not exist and is being expanded to "get_answers()"
We also add the `--warnings-as-errors` option to `mix test` in GitHub
Actions.
=> Fix warnings when `mix test`

reading/built-in_modules.livemd
This part of the lesson is about keyword lists.
=> fix typo in built-in modules section

utils/lib/feedback.ex
Feedback not implemented for the corresponding reading exercise on ranges:
https://github.com/DockYard-Academy/beta_curriculum/blob/fbf67b6289624882ce29d17bc79067ffbb3a41cd/reading/ranges.livemd
In the Elixir cell below, Use `Enum.to_list` enter a range from `3` to `9` with a step of `3`. 
Replace `nil` with your answer.
```elixir
answer = nil
Utils.test(:range_to_list, answer)
```
=> Feedback not implemented for the corresponding reading exercise

exercises/fun_formulas.livemd
=> Fix html in fun-formulas page

exercises/tally_votes.livemd
Keyword lists must always come last in lists and maps.
=> Remove syntax error.

exercises/anagram_solver.livemd, exercises/bomb_defusal.livemd, exercises/candy_store.livemd, exercises/factorial.livemd, exercises/games_rock_paper_scissors.livemd, exercises/mazes.livemd, exercises/mining_simulator.livemd, exercises/rock_paper_scissors_genserver.livemd, exercises/spoonacular_recipe_api.livemd, exercises/video_game_spawner.livemd, reading/command_line.livemd, reading/comprehensions.livemd, reading/enum.livemd, reading/exunit.livemd, reading/iex.livemd, reading/maps.livemd, reading/maps_mapsets_keyword_lists.livemd, reading/mix.livemd, reading/persistence.livemd, reading/scripts.livemd
This PR resolves all warnings raised by markdownlint where the header
ended with punctuation except those with exclamation or question mark.
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026
Something similar to issue https://github.com/DockYard-Academy/beta_curriculum/issues/104
=> Remove trailing punctuation in header (MD026)

.tool-versions, README.md
Note that an incorrect Erlang version was updated from https://github.com/DockYard-Academy/beta_curriculum/pull/129/files
=> Bump Erlang/Elixir versions for asdf

utils/lib/assets/tested_cell/main.js
Simply do not show an empty hint box when the hint is empty
=> Proposal: Making TestedCells hint optional

exercises/home_page.livemd
Tested it and it is working as fontawesome was working before it also has the Github icon we want to use.
=> Changed fontawesome to lineicons

exercises/mad_libs.livemd
I found a strange `HiddenCell` in the middle of Mad Libs livebook.
Maybe used for testing purposes but forgotten to be cleaned since
=> Remove random HiddenCell

README.md
I was having trouble getting the `livebook server` to run due to the command not being found. After some research, I had to perform a reshim on asdf. Instead of other people wasting time getting it to run, it'd be nice to add a quick solution to get things going.
=> add troubleshooting step for unfound livebook command

utils/mix.exs
People using livebook desktop need all dependencies the projects uses to be in the `utils` project until we replace `utils` entirely.
This PR adds `kino_lab` to resolve `Kino.Youtube` not being available.
=> Add kino_lab to utils project

exercises/livebook_recovery.livemd, reading/code_editors.livemd, reading/livebook.livemd
Addresses #65. Current livebook keybindings are windows &linux only. This PR updates relevant `.livemd` files to also mention MacOS keybindings.
=> Add MacOS keybindings where needed

utils/test/utils_test.exs
As said in https://github.com/DockYard-Academy/beta_curriculum/pull/224#discussion_r936067560
It could be a good idea to unify `any_show_editors?` and `any_invalid_links?` to make a `file_contains?` function
=> Refactor: file_contains?

exercises/mad_libs.livemd
I think the possible solution in this block was missing an end quote for the string `code`.
This is what I saw on a fresh version of the workbook.
=> Add missing quote in possible solution recommendation.

reading/arithmetic.livemd, utils/lib/animate.ex
**Issue**
Per the discussions of #196, animations in the Arithmetic Livebook would go on forever.
**Fix**
This change introduces inline use of `SmartAnimation` allowing for the animations to be speed up, stopped, or restarted.
**Notes**
This change is also partial work toward a larger goal of eventually removing all calls to `Utils` described in #176 -- allowing the Livebooks to be more portable and less reliant on libraries that live in this repo but might not be shared with an individual `.livemd` file in the future.
=> [Fixes #196] Replaces use of `Utils.animate/1` with inline `SmartAnimation` calls. 

.tool-versions
Fixes #293
* Removes the nodejs declaration. 
* Updates the elixir version to a newer bug fix and aligns its OTP level with the existing erlang version.
=> [Fixes #293] Updates `.tool-versions`.

reading/file.livemd
=> [Fixes #334] Fixes the referred arity of File.rm to be `File.rm/1`.

reading/code_editors.livemd
Remove in text reference to unused VSCode extension for Surface UI
Extension is currently not a recommended install in extensions.json
=> Issue 371 - Remove reference to unused extension

reading/enum.livemd
The hint currently does not match the expected solution. You need to pass in the initial `acc` value else `reduce/2` will use the first value of the collection.
=> Fix hint in Enum Livebook.

reading/comprehensions.livemd
I have fixed the following typo in a cell code:
`Enum.map(1...5)`
It would be worth double checking that the prior two typos are still fixed. I did so in my current branch to be sure.
Here's where comprehensions get cool and stop looking **like for** loops.
You can use multiple **comma-separate** generators in a single comprehension.
=> Fixed three typos

reading/comprehensions.livemd
Found two typos in the Comprehensions lesson
Here's where comprehensions get cool and stop **looking like for** loops -> Changed into "looking like"
You can use multiple **comma-separate** generators in a single comprehension. -> Changed into "comma-separated"
=> Fixed two typos

reading/phoenix.livemd
The `Counter` was sending a message to `__MODULE__` where `Counter` is not a process, but a client.
Changed to sending to correct named process.
=> Counter was calling to wrong process

exercises/saferange.livemd
I believe the original intention was to show the output of the elixir shell but not present the shell with `iex>` typed in. I could be wrong though.
=> typo fix in safe range exercise

exercises/palindrome.livemd
Remove the given example solution in the palindrome exercise from the elixir shell.
=> Remove palindrome example solution from the shell

exercises/email_validation.livemd, reading/documentation_and_static_analysis.livemd, reading/iex.livemd, reading/metaprogramming.livemd, reading/testing_genservers.livemd
Fixes #504 
Updates the suggested function and link in the hint for Email Validation to match up with the example solution.
The other changes here were changes from `mix bc`
=> Update Email Validation exercise hint to reflect the function used in the example

reading/with.livemd
The given example solution in `reading/with.livemd` does not return the expected results.
=> Fix typos in 'with' example solution

exercises/timeline.livemd
There is a missing ']' in the Timeline example code.
-    iex> Timeline.from_strings(["2020-01-01", "2020-01-02")
+    iex> Timeline.from_strings(["2020-01-01", "2020-01-02"])
=> add missing "]" to timeline examples

exercises/tic-tac-toe.livemd
Fill example for coordinates {0, 0} seems inaccurate - according to graph at the top of the page position 'G' from the previous example:
```
iex> TicTacToe.fill(board, {0, 0}, "X")
-  [[nil, nil, nil], [nil, nil, nil], [nil, nil, "X"]]
+  [[nil, nil, nil], [nil, nil, nil], ["X", nil, nil]]
```
Also a few whitespace suggestions
=> fix solution example for coordinates {0,0}

exercises/typespec_drills.livemd
Changed Example Solution to use `String.t()` instead of `string()`
=> Updated Example Solution in exercises/typespec_drills.livemd

reading/processes.livemd
Scaffolding invoked the incorrect module, which is unmodified to receive `:decrement`. 
`CounterProcess` vs `Counter`
=> Correct Counter :decrement exercise

reading/generic_server.livemd
Updated your turn segment,;changed `Notebook` to `NoteBook`, matching module name in instructions and setup documentation.
=> Update generic_server.livemd - Fix module name

reading/processes.livemd
The example had:
```
pid1 = ...
Process.link(pid)
```
Changed it to:
```
Process.link(pid1)
```
=> added the correct pid variable name to example

exercises/timer.livemd
Starter code for the exercise was all commented out.
=> timer.livemd uncomment starter code

exercises/traffic_light_server.livemd
Fixing slight module name mismatch that was causing confusion.
=> Updated Traffic Light example usage to match module definition

exercises/saferange.livemd
Example implementation uses invalid variable names and incorrectly raised on all ranges where first > last.
=> Correct example implementation of SafeRange

exercises/supervisor_and_genserver_drills.livemd
Hi @BrooklinJazz,  going through this exercise, I found out that the Example Solution was missing a handle_cast/2 function, so I added it =). 
Also, an instruction asks us to use a GenServer.init/1 function. So I changed it to State.init/1, cause I couldn't find on the documentation a GenServer.init/1 function.
Please check if my thoughts are on the right direction =)
=> exercise sugestion

reading/html_css.livemd
**Description**
Changes the example of CSS child & descendent, to include grandchilds
**Issues**
https://github.com/DockYard-Academy/beta_curriculum/issues/621
=> Changes the example of CSS child & descendent, to include grandchilds

reading/apis.livemd
Hi @BrooklinJazz  =)
On the HTTP request, the value in the body key was "value" and not "test," as mentioned in the paragraph above, causing an error. I don't know if it was on purpose so that the students could change it for themselves, but since I haven't seen any clear command to do so, I decided to send this PR =)
=> changed body on http request

reading/livebook.livemd
- when Evaluated becomes italicized to indicate that a cell has changed since last evaluated, it is also followed by an asterisk
- unnecessary comma
=> correction, punctuation in reading/livebook > evaluation section

exercises/caesar_cypher.livemd
The Example Solution in Caesar Cypher exercise has an off-by-one error in `CaesarCyphe.encode/2` while shifting from 'z' to 'a'. 
**Current function definition**
**Resulting in**
```shell
iex(1)> CaesarCyphe.encode("z", 1)
"b"
iex(2)> CaesarCyphe.encode("z", 2)
"c"
```
=> Fix Off-by-one error in Caesar Cypher

reading/schemas_and_migrations.livemd
Removed duplicate link to Ecto docs. This link was made one sentence prior.   Small grammar clean up.  
The following sentence appears more than once in the reading. It is relevant in both places I noticed it, however it has not been the norm to so closely repeat data in a reading. 
> It's important to note that Ecto will only apply unapplied migrations, so you can safely run the ecto.migrate task multiple times without worrying about making the same changes to the database more than once. This can be very useful for managing the evolution of your database over time.
=> Grammar and structure cleanup

exercises/filter_values_by_type.livemd
- Replaced the usage of `is_integer/1` and `is_float/1` with `is_number/1`
- Handled empty list for test case
=> Fix `Filter Values By Type` solution

exercises/pokemon_battle.livemd
- After the attack, the resulting struct should be of the defender Pokemon. But in case of `Type Advantage` we have the attacker struct being return in the doc test.
=> Fix pokemon exercises doc test

exercises/time_converting.livemd
- As per the doc tests the returning unit of time should be in float.
=> Fix example solution in time converting excersice

exercises/math_with_guards.livemd
- The doc tests for `FunctionClauseError` fails since the exception message contains trailing space.
=> Remove trailing space and fix doc tests in math_with_guards

reading/strings_and_binaries.livemd
- Decimal `10` maps to `a` in hexadecimal but in the table it maps to `10` in hexadecimal.
**Before**
**After**
=> Fix decimal-hexdecimal table values

exercises/mailbox_server.livemd
- `handle_call` isn't used as part of requirement so replaced `GenServer.call` with `GenServer.cast`.
- Fix the unused variable warning for pid.
=> Fix Mailbox Server solution

.tool-versions
Erlang 25.2.1 seems to be causing many people asdf issues, so I'm downgrading back to 25.1.2.
=> downgrade erlang version

exercises/rock_paper_scissors.livemd
Correct the way of how we call the function expression (causing error on example code). It should be with dot notation instead of calling it like regular function.
```
hello = fn -> "hello" end
hello.() # we need dot notation when calling the function expression
```
=> fix: correct the way fo calling function expression

reading/livebook.livemd
Before: using alt+shift+f for formatting the code doesn't give any effect. the formatting option of livebook (right mouse on cell) make it clear that it should be ctrl+shift+i
After: change the instructed keybinding for formatting to ctrl+shift+i and for mac is instead of using ...+...+f we use ...+...+i
=> Fix wrong formatting keybinding on livebook section

reading/advanced_pattern_matching.livemd
Minor typos fix and adding Yusef's doc tests(#813)  to `Converter.to_named_strings/1`.
=> Fix minor typos in Advanced Pattern Matching reading material

exercises/anagram.livemd
In the example solution, the function `anagram?` parameter names were `string1` and `string2`, but then later in the function the variables were referred to as `word` and `possible_anagram`. I've updated all instances of `string1` and `string2`.
=> fix difference in variable names

reading/enum.livemd
`animals` variable is mentioned in the explanation, but missing in block code. I think it will be much clearer to write it (because it's already mentioned)
=> Fix missing animals variable

reading/enum.livemd
Varibale `to_find` doesn't add any value, so I think it much better to remove it
=> Remove unnecessary to_find variable

exercises/filter_values_by_type.livemd
The instruction is to
> Filter in lists and keyword lists in list.
So I'm adding the missing empty list which is count as keyword list on test result
=> Fix missing keyword list in test result

exercises/filter_values_by_type.livemd, exercises/measurements.livemd
Existing doctest did not include an empty list `[ ]` as an expected output, so the doctest was failing.
=> Filter values fix doctest for lists

exercises/filter_values_by_type.livemd
I think it's better to make it clear that empty list is count as keyword list so the student will end up with more concise code and better understanding
=> Simplify exercise copy instruction on filter value by type

exercises/measurements.livemd
The example solution for the `average` function does not currently pass the doctests, because an integer is expected, and the current solution produces a float. Hence I've updated the division to use div/2 rather than simple division.
I've also re-arranged the order of the functions in the module to match the example solution, so `increments` comes before `increased`. I believe this order is also more intuitive when solving the problem (as I discovered for myself).
**Screenshots**
The current example solution for `average`:
The issue with that:
=> Update example solution for Measurements exercise

exercises/filter_values_by_type.livemd, exercises/measurements.livemd, reading/mix.livemd
Currently the code cell is outputting an error, because Livebook won't let it re-define the module HelloWorld (it's been defined in a previous cell in). We can leave it as is, the error is just a little confusing. I thought converting it to a markdown cell made the most sense. We can't change the module name, because it's referring to an existing module in the Mix project.
=> Mix reading change to markdown

reading/enum.livemd
Enum.any?/1 function is missing ? on the livebook
Before: `Enum.any/1`
After: `Enum.any?/1`
=> Add missing ? on Enum.any

reading/git.livemd
A bulleted list in `git.livemd` at line 56 was missing Markdown formatting for the list and text, causing an incongruous render for one item.
The section on `Branching` renders in line with the `Pull Request` section:
`Branching` is a bullet point and bold like the rest of the list:
=> Correct the bulleted list of GitHub key features

reading/big_o_notation.livemd
The final table was miscalculating the factorial results, which has been fixed.
A further error where 4**2 = 12 has been updated to 16.
=> fix error in factorial table

CONTRIBUTING.md, reading/regex.livemd
Hey hey!
The links for Regexr in Regex and the fork link in Contributing are nested/invalid markdown links in the form of:
`[link title]([nested title that breaks the link](http://link.com))`
This PR corrects both of these links with well-formed markdown links!
=> Fix Regexr and fork links

reading/livebook.livemd
Dunno about the windows/linux shortcuts but the previously correct cmd+option+F is still valid on macOS in livebook v0.9.0.
=> Fix formating shortcuts for mac

exercises/fun_formulas.livemd
The example solution does not include the multiplication with 100 and could be confusing as this is in the percent calculation formula right above.
=> Fixes percent calculation

reading/supervisors.livemd
Changed this code # Spawn_link(fn -> Raise "error" End) to be lower case
=> Fixed minor typo in Supervisors 

reading/strings.livemd
The whole special character being escaped is the string interpolation`#{}`; you can think of this as escaping the leading hash symbol leaves everything else as just normal characters or as escaping the whole interpolation token. It is unnecessary to escape each individual character in the string interpolation.   You wouldn't need to do `\#\{\2\+\2\}` to include `#{2+2}` in a string rather that have Elixir interpolate it and return 4, `\#{2+2}` will do that. The whole interpolation is escaped with a single backslash.
=> Clean up escaping string interpolation example

exercises/habit_tracker.livemd
You're asking for percent and give a reminder to multiply by 100 to get percent but the suggested solution leave the proportion.
You may choose not to include the parenthesis that I did; I like to explicitly indicate the expected order of operations as formulas are easier for me to read them that way.
=> Convert proportion to percent

reading/datetime.livemd
Missing "override: true" on kino dependency
=> datetime.livemd kino dependency fix

reading/phoenix_and_ecto.livemd
in ecto docs it says
> The unique constraint works by relying on the database to check if the unique constraint has been violated or not and, if so, Ecto converts it into a changeset error.
so if you do not do this it will not show error when you insert new post with title already exists and just inserted
=> Add unique index for title

reading/supervisors.livemd
It was failing because `strategy: :one_for_one, max_restarts: 5` had capital letters.
=> Superviors failing because of capital letters in Strategy: and Max_restarts:

reading/enum.livemd
> Use [Enum.map/2](https://hexdocs.pm/elixir/Enum.html#map/2) to convert a list of integers from 1 to 10 to strings.
=> fix: expected output of Enum.map to str collection in Enum reading

reading/enum.livemd, reading/non_enumerables.livemd
Caught what I assume is an unintended wording. Thanks for having this curriculum open to the public!
Edit: In this same chapter (Enum), the function `Enum.all?/2` was typically (but not always) missing the question mark in markdown references to it. Updated all of those as well.
=> Enum chapter fixes

reading/exunit.livemd
The first executable test with the `=~` operator in the ExUnit reading was missing an assert function, so nothing was actually being tested.
=> add missing assert in string test

exercises/phoenix_follow_along_counter_app.livemd
- the name of the action in the `CounterController` should be `:count` instead of `:home` in `router.ex`
=> Fix the errors when incrementing the counter value

exercises/blog_posts.livemd, exercises/traffic_light_server.livemd, reading/phoenix_and_ecto.livemd
Also added a fix to the Traffic Light Server exercise where module names had typos and were named inconsistently throughout.
=> Phoenix and Ecto section fixes

reading/apis.livemd, reading/phoenix_authentication.livemd, reading/phoenix_one_to_many_associations.livemd
Edit: Also fixed the joke API call in the API reading, which sometimes would grab jokes of a format not compatible with the decoding example.
=> fix typos in one to many reading

exercises/phoenix_drills.livemd, exercises/phoenix_follow_along_counter_app.livemd, reading/phoenix_1.7.livemd, reading/phoenix_components.livemd
A tiny typo in the name of `Phoenix.Component`
=> Fix typo in phoenix components section

exercises/rpg_dialogue.livemd
First, the test itself *should* work because the character has a `:name`, so I can't get that test to "pass". When changing it so it does throw an error, the whole liveview process throws an error:
Options I attempted:
1. I tried the original with no name passed to the struct
2. I tried using `assert_raise` with the third param, including the message but isn't required and made the test long (and still failed) 
3. I tried to use `assert_raise` as well but the argument error is still propagated to the livebook, and kills compilation.
```elixir
iex> assert_raise ArgumentError, fn -> %Character{} end
:ok
```
=> fix: Remove argumentError doctest

reading/modules.livemd
Issue #1062 
Update explanation on Modules -> Multiple Function Clauses fixing the name of the defined multiple function created as example and its arities.
The goal is to keep the explanation related to the example.
=> Update Modules -> Multiple Function Clauses arity explanation
